### ISSUE TITLE
Issue retrieving model from ray -- Permission denied

### ISSUE THREAD

**Issue by rajesh-chawla** [ray-project/mlflow-ray-serve#10]
Hi folks,

I'm having issues retrieving a mlflow model from a ray cluster using mlflow deployment. In the stack trace I see. 
```
(ServeController pid=17178) PermissionError: [Errno 13] Permission denied: '/mlruns'
```

I've started a ray cluster using the commands:
```
ray start --head
serve start
```

The specific command I'm executing is:
```
mlflow deployments create -t ray-serve -m models:/White-Wine/4 --name RajeshOnnxWine
```

Items I've tried / done:

- tried setting MLFLOW_TRACKING_URI to http://localhost:5001, which is where I view the MLFlow UI
- tried setting MLFLOW_TRACKING_URI  to 'postgresql://postgres@groq1.entanglement.ai:6789/mlflow', which is the location of the model repository in PostgreSQL
- verified that where I run mlflow has access to the artifact root.

Any thoughts on how to avoid the error for Permission denied on /mlruns.

Regards,
Rajesh

**Comment by architkulkarni** [comment]
Hi Rajesh, it looks like this is related to the MLflow setup, as the plugin is doing something pretty simpleminded: https://github.com/ray-project/mlflow-ray-serve/blob/86ee78039bbd535da760f70a084aa0ab22d50f15/mlflow_ray_serve/__init__.py#L48

Does `mlflow.pyfunc.load_model` work for you in isolation with your model URI? If not, perhaps you'll be able to get more help from the MLflow community.

**Comment by architkulkarni** [comment]
Also, does the example given here work for you? https://github.com/mlflow/mlflow/tree/master/examples/ray_serve. It does something a bit different with the tracking URI.

**Comment by rajesh-chawla** [comment]
@architkulkarni Appreciate the responses. In process of verifying.

**Comment by rajesh-chawla** [comment]
Verified fix from MLflow.
